SRC_CPPS = \
           main.cpp \
           pvdualsourcesample.cpp \
           source.cpp \
           sourcewidget.cpp \
           threaddisplay.cpp \

EXEC     = PvDualSourceSample

include ../sample.Makefile
