// generated by Fast Light User Interface Designer (fluid) version 1.0300

#include "gui.h"

void Gui::cb_Quit_i(Fl_Menu_*, void*) {
  exit(1);
}
void Gui::cb_Quit(Fl_Menu_* o, void* v) {
  ((Gui*)(o->parent()->user_data()))->cb_Quit_i(o,v);
}

Fl_Menu_Item Gui::menu_menuBar[] = {
 {"FOXSI GSE", 0,  0, 0, 64, FL_NORMAL_LABEL, 1, 14, 0},
 {"About FOXSI GSE", 0,  0, 0, 0, FL_NORMAL_LABEL, 0, 14, 0},
 {"Preferences...", 0,  0, 0, 0, FL_NORMAL_LABEL, 0, 14, 0},
 {"Quit", 0x400071,  (Fl_Callback*)Gui::cb_Quit, 0, 0, FL_NORMAL_LABEL, 0, 14, 0},
 {0,0,0,0,0,0,0,0,0},
 {"File", 0,  0, 0, 64, FL_NORMAL_LABEL, 0, 14, 0},
 {0,0,0,0,0,0,0,0,0},
 {"Window", 0,  0, 0, 64, FL_NORMAL_LABEL, 0, 14, 0},
 {"Commanding", 0,  0, 0, 0, FL_NORMAL_LABEL, 0, 14, 0},
 {"ACTEL Commanding", 0,  0, 0, 0, FL_NORMAL_LABEL, 0, 14, 0},
 {0,0,0,0,0,0,0,0,0},
 {0,0,0,0,0,0,0,0,0}
};
Fl_Menu_Item* Gui::fileMenu = Gui::menu_menuBar + 5;
Fl_Menu_Item* Gui::menuProc = Gui::menu_menuBar + 7;

void Gui::cb_test_i(Fl_Button*, void*) {
  app->run_test();
}
void Gui::cb_test(Fl_Button* o, void* v) {
  ((Gui*)(o->parent()->user_data()))->cb_test_i(o,v);
}

Gui::Gui() {
  { mainWindow = new Fl_Double_Window(958, 701, "FOXSI GSE");
    mainWindow->color((Fl_Color)19);
    mainWindow->user_data((void*)(this));
    { menuBar = new Fl_Menu_Bar(-5, -1, 1460, 26, "menuBar");
      menuBar->box(FL_BORDER_BOX);
      menuBar->color((Fl_Color)29);
      menuBar->menu(menu_menuBar);
    } // Fl_Menu_Bar* menuBar
    { Fl_Group* o = new Fl_Group(35, 58, 440, 532, "Image");
      { detectorsImageWindow = new detectorsImage(60, 80, 300, 300);
        detectorsImageWindow->box(FL_NO_BOX);
        detectorsImageWindow->color(FL_BACKGROUND_COLOR);
        detectorsImageWindow->selection_color(FL_BACKGROUND_COLOR);
        detectorsImageWindow->labeltype(FL_NORMAL_LABEL);
        detectorsImageWindow->labelfont(0);
        detectorsImageWindow->labelsize(14);
        detectorsImageWindow->labelcolor(FL_FOREGROUND_COLOR);
        detectorsImageWindow->align(Fl_Align(FL_ALIGN_CENTER));
        detectorsImageWindow->when(FL_WHEN_RELEASE);
      } // detectorsImage* detectorsImageWindow
      o->end();
    } // Fl_Group* o
    { consoleBuf = new Fl_Text_Display(515, 30, 500, 145);
    } // Fl_Text_Display* consoleBuf
    { Fl_Button* o = new Fl_Button(515, 190, 70, 20, "test");
      o->callback((Fl_Callback*)cb_test);
    } // Fl_Button* o
    mainWindow->end();
  } // Fl_Double_Window* mainWindow
  app=new Application();
  buff=new Fl_Text_Buffer();
  consoleBuf->buffer(buff);
  prefs=new Fl_Preferences(Fl_Preferences::USER, "sdc", "HEROES SAS GSE");
  // initialization
}

void Gui::show() {
  mainWindow->show();
  detectorsImageWindow->show();
}
