// generated by Fast Light User Interface Designer (fluid) version 1.0300

#ifndef gui_h
#define gui_h
#include <FL/Fl.H>
#include <FL/Fl_Double_Window.H>
#include "Application.h"
#include <stdlib.h>
#include <FL/Fl_Menu_Bar.H>
#include <FL/Fl_Group.H>
#include "detectorsImage.h"
#include <FL/Fl_Text_Display.H>
#include <FL/Fl_Button.H>

class Gui {
public:
  Gui();
  Fl_Double_Window *mainWindow;
  Fl_Menu_Bar *menuBar;
  static Fl_Menu_Item menu_menuBar[];
private:
  void cb_Quit_i(Fl_Menu_*, void*);
  static void cb_Quit(Fl_Menu_*, void*);
public:
  static Fl_Menu_Item *fileMenu;
  static Fl_Menu_Item *menuProc;
  detectorsImage *detectorsImageWindow;
  Fl_Text_Display *consoleBuf;
private:
  void cb_test_i(Fl_Button*, void*);
  static void cb_test(Fl_Button*, void*);
public:
  void show();
  Application *app; 
  Fl_Text_Buffer *buff; 
  Fl_Preferences *prefs; 
};
#endif
